export const estados = [
  { codigo: 12, estado: "Acre" },
  { codigo: 27, estado: "Alagoas" },
  { codigo: 16, estado: "Amapá" },
  { codigo: 13, estado: "Amazonas" },
  { codigo: 29, estado: "Bahia" },
  { codigo: 23, estado: "Ceará" },
  { codigo: 53, estado: "Distrito Federal" },
  { codigo: 32, estado: "Espírito Santo" },
  { codigo: 52, estado: "Goiás" },
  { codigo: 21, estado: "Maranhão" },
  { codigo: 51, estado: "Mato Grosso" },
  { codigo: 50, estado: "Mato Grosso do Sul" },
  { codigo: 31, estado: "Minas Gerais" },
  { codigo: 15, estado: "Pará" },
  { codigo: 25, estado: "Paraíba" },
  { codigo: 41, estado: "Paraná" },
  { codigo: 26, estado: "Pernambuco" },
  { codigo: 22, estado: "Piauí" },
  { codigo: 33, estado: "Rio de Janeiro" },
  { codigo: 24, estado: "Rio Grande do Norte" },
  { codigo: 43, estado: "Rio Grande do Sul" },
  { codigo: 11, estado: "Rondônia" },
  { codigo: 14, estado: "Roraima" },
  { codigo: 42, estado: "Santa Catarina" },
  { codigo: 35, estado: "São Paulo" },
  { codigo: 28, estado: "Sergipe" },
  { codigo: 17, estado: "Tocantins" },
];
