name: DEV - Create Pull Request

on:
  push:
    branches: ["feature/**"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-feature:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]
    steps:
      - name: Checkout Build
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --quiet

      # - name: Build Project
      #   run: yarn build
  createPullRequest:
    runs-on: ubuntu-latest
    needs: [build-feature]
    steps:
      - name: Checkout Build
        uses: actions/checkout@v4

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: 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
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          draft: false
          commit-message: Update report
          assignees: ltisistemas
          reviewers: ltisistemas
          signoff: false
          branch: develop
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/ltisistemas/mini-erp-comercial

      # - name: Create or Update Project Card
      #   if: ${{ steps.cpr.outputs.pull-request-number }}
      #   uses: peter-evans/create-or-update-project-card@v2
      #   with:
      #     column-name: PR
