name: Build Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build Project
        run: yarn build
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Release
        uses: actions/checkout@v4
      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
