name: Build Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Build
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install --quiet
      - name: Build Project
        run: yarn build
      - name: Deploy GH Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/lti-mini-erp-comercial
          enable_jekyll: true
  # release:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout Release
  #       uses: actions/checkout@v4
  #     - name: Create release
  #       uses: Roang-zero1/github-create-release-action@v2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
